### ISSUE TITLE
Ruby group capstone: set up Kanban board

### ISSUE THREAD

**Issue by ghost** [melaniesigrid/catalog-of-things#21]
In this P.R.

- [x] Create project Kanban board.
- [x] Divided tasks equally.
- [x] Each task is a separated card.

Team members:

- Team member 1: @melaniesigrid 
- Team member 2:  @fabgrel10 
- Team member 3: @gabyse1

Project Link: [https://github.com/melaniesigrid/catalog-of-things](https://github.com/melaniesigrid/catalog-of-things)

To the reviewer: Thank you in advance for your review!

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍 
-  Kanban board  is set up correctly ✔️ 
-  Each card on the board has title, points and description  ✔️ 
- All cards are assigned to team members ✔️ 
- Tasks are distributed in a fair way✔️ 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
